[en]
  languageCode = 'en-US'
  languageDirection = 'ltr'
  languageName = 'English'
  weight = 1
  [en.menu]
  [[en.menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "post"
    weight = 10

  [[en.menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "about"
    weight = 20

[nl]
  languageCode = 'nl-NL'
  languageDirection = 'ltr'
  languageName = 'Nederlands'
  weight = 2
  [nl.menu]
  [[nl.menu.main]]
    identifier = "post"
    name = "Blog"
    pageRef = "post"
    weight = 10

  [[nl.menu.main]]
    identifier = "about"
    name = "Over"
    pageRef = "about"
    weight = 20