baseurl = "http://www.nickhartjes.com"
title = "nickhartjes"

theme = "hugo-coder"

languagecode = "nl"
defaultcontentlanguage = "nl"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "nickhartjes"

[params]
    author = "Nick Hartjes"
    description = "Nick Hartjes's persoonlijke website"
    keywords = "blog,developer,personal"
    info = "Full Stack DevOps and Magician"
    avatarurl = "images/avatar.jpg"
    #gravatar = "john.doe@example.com"
    footercontent = "Enter a text here."

    dateformat = "2 January, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"
    
# If you want to use plausible(https://plausible.io) for analytics, add this section
[params.plausibleAnalytics]
    domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/nickhartjes/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/nickhartjes/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/nickhartjes/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 4
    url = "https://medium.com/@nickhartjes/"

[languages]
    [languages.en]
        languagename = "English"

        [languages.nl.params]
            keywords = "blog,developer,personal"
            info = "Full Stack DevOps and Magician"
            description = "Personal site of Nick Hartjes"
            footercontent = ""

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"


    [languages.nl]
        languagename = "Nederlands"

        [languages.nl.menu]

            [[languages.nl.menu.main]]
            name = "Over"
            weight = 1
            url = "about/"

            [[languages.nl.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.nl.menu.main]]
            name = "Projecten"
            weight = 3
            url = "projects/"

            [[languages.nl.menu.main]]
            name = "Contact"
            weight = 5
            url = "contact/"